# Generated by Django 4.0 on 2022-01-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'Faol emas'), (2, 'Faol'), (3, 'Mavjud emas'), (4, 'Yangi qo`shilmoqchi')], default=2)),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('middlename', models.CharField(blank=True, max_length=30, null=True)),
                ('social', models.JSONField(blank=True, default={'fb': '', 'git': '', 'ins': '', 'tg': ''}, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(default=True)),
                ('is_student', models.BooleanField(default=True)),
                ('join_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_serial', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Mavjud emas'), (2, 'Faol'), (3, 'Yangi qo`shilmoqchi')], default=2)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_district', to='geo.district')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='company.position')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_region', to='geo.region')),
            ],
            options={
                'verbose_name': 'Xodim va a`zo',
                'verbose_name_plural': 'Xodimlar va A`zolar',
            },
        ),
    ]
