# Generated by Django 4.0 on 2022-01-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lang', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Ruskiy')], max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.SmallIntegerField(choices=[(1, 'Faol emas'), (2, 'Faol'), (3, 'Mavjud emas'), (4, 'Yangi qo`shilmoqchi')], default=2)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_month', models.IntegerField(default=0)),
                ('assistant', models.ForeignKey(blank=True, limit_choices_to={'is_student': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers2', to='company.member')),
                ('course', models.ForeignKey(blank=True, limit_choices_to={'active_status': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_course', to='education.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_student': False}, on_delete=django.db.models.deletion.CASCADE, related_name='teachers1', to='company.member')),
            ],
            options={
                'verbose_name': 'O`quv Gruh',
                'verbose_name_plural': 'Gruppalar',
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.SmallIntegerField(choices=[(1, 'Faol emas'), (2, 'Faol'), (3, 'Mavjud emas'), (4, 'Yangi qo`shilmoqchi')], default=2)),
                ('joined_date', models.DateField()),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='education.group')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='group_student', to='company.member')),
            ],
            options={
                'verbose_name': 'Guruh Talabasi',
                'verbose_name_plural': 'Talabalar',
                'unique_together': {('student', 'group')},
            },
        ),
    ]
